USE Targit_Model
GO

ALTER VIEW VIEW_DIM_Time AS
SELECT TOP 100 PERCENT
	ROW_NUMBER() OVER(ORDER BY TM_Hour, TM_Minute) AS PKEY, 
	TM_Hour, 
	TM_Minute, 
	RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) AS Hour_Text,
	RIGHT('00' + CAST(TM_Minute AS VARCHAR(10)),2) AS Minute_Text,
	CASE 
		WHEN TM_Minute BETWEEN 0 AND 29 THEN RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':00' 
		WHEN TM_Minute BETWEEN 30 AND 59 THEN RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':30'
	END AS HalfHour_Text,
	CASE 
		WHEN TM_Minute BETWEEN 0 AND 14 THEN RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':00' 
		WHEN TM_Minute BETWEEN 15 AND 29 THEN RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':15'
		WHEN TM_Minute BETWEEN 30 AND 44 THEN RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':30'
		WHEN TM_Minute BETWEEN 45 AND 59 THEN RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':45'
	END AS Quarter_Text,
	RIGHT('00' + CAST(TM_Hour AS VARCHAR(10)),2) + ':' + RIGHT('00' + CAST(TM_Minute AS VARCHAR(10)),2) AS TM_Description,
	CASE WHEN MAX(A.PKEY) BETWEEN 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, DATEADD(MINUTE, -5, GETDATE())) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, DATEADD(MINUTE, -5, GETDATE())) AS VARCHAR(10)),2) + ':00'
	) 
	AND 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, GETDATE()) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, GETDATE()) AS VARCHAR(10)),2) + ':00'
	) 
	THEN 1 ELSE 0 END
	AS Last_05_Min_Flag,
	CASE WHEN MAX(A.PKEY) BETWEEN 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, DATEADD(MINUTE, -15, GETDATE())) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, DATEADD(MINUTE, -15, GETDATE())) AS VARCHAR(10)),2) + ':00'
	) 
	AND 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, GETDATE()) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, GETDATE()) AS VARCHAR(10)),2) + ':00'
	) 
	THEN 1 ELSE 0 END
	AS Last_15_Min_Flag,
	CASE WHEN MAX(A.PKEY) BETWEEN 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, DATEADD(MINUTE, -30, GETDATE())) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, DATEADD(MINUTE, -30, GETDATE())) AS VARCHAR(10)),2) + ':00'
	) 
	AND 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, GETDATE()) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, GETDATE()) AS VARCHAR(10)),2) + ':00'
	) 
	THEN 1 ELSE 0 END
	AS Last_30_Min_Flag,
	CASE WHEN MAX(A.PKEY) BETWEEN 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, DATEADD(MINUTE, -60, GETDATE())) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, DATEADD(MINUTE, -60, GETDATE())) AS VARCHAR(10)),2) + ':00'
	) 
	AND 
	(
		SELECT PKEY FROM tb_TRGMDL_Time WITH (NOLOCK) WHERE TM_Description = 
		RIGHT('00' + CAST(DATEPART(HOUR, GETDATE()) AS VARCHAR(10)),2) + ':' 
		+ RIGHT('00' + CAST(DATEPART(MINUTE, GETDATE()) AS VARCHAR(10)),2) + ':00'
	) 
	THEN 1 ELSE 0 END
	AS Last_60_Min_Flag,
	CASE 
		WHEN TM_Hour BETWEEN 0 AND 5 THEN 1
		WHEN TM_Hour BETWEEN 6 AND 11 THEN 2
		WHEN TM_Hour BETWEEN 12 AND 17 THEN 3
		WHEN TM_Hour BETWEEN 18 AND 23 THEN 4
	END AS DayPart_ID,
	CASE 
		WHEN TM_Hour BETWEEN 0 AND 5 THEN 'After Midnight'
		WHEN TM_Hour BETWEEN 6 AND 11 THEN 'Morning'
		WHEN TM_Hour BETWEEN 12 AND 17 THEN 'Afternoon'
		WHEN TM_Hour BETWEEN 18 AND 23 THEN 'Evening'
	END AS DayPart_Name,
	CASE 
		WHEN TM_Hour BETWEEN 0 AND 5 THEN 'Μεσάνυχτα - Ξημέρωμα'
		WHEN TM_Hour BETWEEN 6 AND 11 THEN 'Πρωί'
		WHEN TM_Hour BETWEEN 12 AND 17 THEN 'Μεσημέρι'
		WHEN TM_Hour BETWEEN 18 AND 23 THEN 'Απογευμα - Βράδυ'
	END AS DayPart_Name_GR
FROM tb_TRGMDL_Time A WITH (NOLOCK)
GROUP BY
	TM_Hour, TM_Minute
ORDER BY 1, 2

GO


